### ISSUE TITLE
EPIC: Cosmos integration readiness in Babylon node

### ISSUE THREAD

**Issue by SebastianElvis** [babylonlabs-io/babylon#272]
## High priority features

- [x] https://github.com/babylonlabs-io/pm/issues/43
- [x] https://github.com/babylonlabs-io/babylon/issues/280
- [x] https://github.com/babylonlabs-io/babylon/issues/1240
- [x] https://github.com/babylonlabs-io/pm/issues/436
- [x] https://github.com/babylonlabs-io/babylon/issues/1237
- [x] https://github.com/babylonlabs-io/babylon/issues/1239
- [x] https://github.com/babylonlabs-io/babylon/issues/1240

## Integration spec

- [ ] https://github.com/babylonlabs-io/pm/issues/163
- [ ] https://github.com/babylonlabs-io/pm/issues/164
- [ ] https://github.com/babylonlabs-io/pm/issues/25

## Bugs

- [ ] https://github.com/babylonlabs-io/babylon/issues/422

## Docs

- [x] #427
- [x] #428

## Nice to have

- [x] https://github.com/babylonlabs-io/pm/issues/119
- [x] #423
- [ ] https://github.com/babylonlabs-io/babylon/issues/164

**Comment by SebastianElvis** [comment]
Major ones are closed. Closing this Github issue and we are tracking the rest in separate Github issues
